package com.sdercolin.vlabeler.ui.string

import com.sdercolin.vlabeler.ui.string.Strings.*

fun Strings.uk(): String = when (this) {
    AppName -> "vLabeler"
    MenuFile -> "Файл"
    MenuFileNewProject -> "Новий проєкт..."
    MenuFileOpen -> "Відкрити..."
    MenuFileOpenRecent -> "Відкрити нещодавні"
    MenuFileOpenRecentClear -> "Очистити список нещодавно відкритих"
    MenuFileQuickEdit -> "Швидке редагування"
    MenuFileSave -> "Зберегти"
    MenuFileSaveAs -> "Зберегти як..."
    MenuFileProjectSetting -> "Налаштування проєкту..."
    MenuFileImportProject -> "Імпортувати проєкт..."
    MenuFileReloadLabelFile -> "Перезавантажити файл міток"
    MenuFileReloadLabelFilePickFile -> "З файлу..."
    MenuFileReloadLabelFileDefault -> "З вихідного файлу..."
    MenuFileReloadLabelFileDefaultWithoutConfirmation -> "З вихідного файлу (без підтвердження)"
    MenuFileExport -> "Експортувати файл міток..."
    MenuFileExportOverwrite -> "Експортувати файл міток із перезаписом"
    MenuFileExportOverwriteAll -> "Експортувати всі файли міток із перезаписом"
    MenuFileInvalidateCaches -> "Анулювати кеші"
    MenuFileClose -> "Закрити"
    MenuEdit -> "Редагування"
    MenuEditUndo -> "Скасувати"
    MenuEditRedo -> "Повторити"
    MenuEditTools -> "Інструменти"
    MenuEditToolsCursor -> "Курсор"
    MenuEditToolsScissors -> "Ножиці"
    MenuEditToolsPan -> "Панорамування"
    MenuEditToolsPlayback -> "Відтворення"
    MenuEditRenameEntry -> "Перейменувати поточний запис..."
    MenuEditDuplicateEntry -> "Дублювати поточний запис..."
    MenuEditRemoveEntry -> "Видалити поточний запис..."
    MenuEditMoveEntry -> "Перемістити поточний запис до..."
    MenuEditToggleDone -> "Перемкнути статус 'Готово' для поточного запису"
    MenuEditToggleStar -> "Перемкнути статус 'Вибране' для поточного запису"
    MenuEditEditTag -> "Редагувати тег поточного запису"
    MenuEditEditEntryExtra -> "Редагувати додаткову інформацію поточного запису"
    MenuEditMultipleEditMode -> "Редагувати всі пов'язані записи"
    MenuEditEditModuleExtra -> "Редагувати додаткову інформацію поточного підпроєкту"
    MenuView -> "Вигляд"
    MenuViewToggleMarker -> "Показати контролери параметрів"
    MenuViewPinEntryList -> "Закріпити список записів"
    MenuViewPinEntryListLocked -> "Заблокувати роздільник для закріпленого списку записів"
    MenuViewToggleProperties -> "Показати властивості"
    MenuViewToggleToolbox -> "Показати панель інструментів"
    MenuViewToggleTimescaleBar -> "Показати лінійку шкали часу"
    MenuViewOpenSampleList -> "Список семплів"
    MenuViewVideo -> "Показати пов'язане відео"
    MenuViewVideoOff -> "Вимкнено"
    MenuViewVideoEmbedded -> "Вбудоване"
    MenuViewVideoNewWindow -> "У новому вікні"
    MenuNavigate -> "Навігація"
    MenuNavigateOpenLocation -> "Відкрити розташування"
    MenuNavigateOpenLocationRootDirectory -> "Кореневий каталог семплів"
    MenuNavigateOpenLocationModuleDirectory -> "Каталог семплів поточного підпроєкту"
    MenuNavigateOpenLocationProjectLocation -> "Розташування файлу проєкту"
    MenuNavigateNextEntry -> "Перейти до наступного запису"
    MenuNavigatePreviousEntry -> "Перейти до попереднього запису"
    MenuNavigateNextSample -> "Перейти до наступного семплу"
    MenuNavigatePreviousSample -> "Перейти до попереднього семплу"
    MenuNavigateJumpToEntry -> "Перейти до запису..."
    MenuNavigateNextModule -> "Перейти до наступного підпроєкту"
    MenuNavigatePreviousModule -> "Перейти до попереднього підпроєкту"
    MenuNavigateJumpToModule -> "Перейти до підпроєкту..."
    MenuNavigateScrollFit -> "Прокрутити, щоб показати поточний запис"
    MenuTools -> "Інструменти"
    MenuToolsBatchEdit -> "Пакетне редагування"
    MenuToolsBatchEditQuickLaunchManager -> "Налаштування слотів..."
    MenuToolsBatchEditQuickLaunch -> "Слот %d: %s"
    MenuToolsBatchEditShowDisabledItems -> "Показати плагіни, які неможливо використовувати в поточному проєкті"
    MenuToolsBatchEditManagePlugins -> "Керування плагінами..."
    MenuToolsPrerender -> "Попередньо відтворити всі графіки..."
    MenuToolsSyncSample -> "Перетворити всі значення відносно кінця семплу..."
    MenuToolsRecycleMemory -> "Звільнити пам'ять"
    MenuToolsFileNameNormalizer -> "Нормалізатор імен файлів..."
    MenuSettings -> "Налаштування"
    MenuSettingsPreferences -> "Параметри..."
    MenuSettingsLabelers -> "Міткувальники..."
    MenuSettingsTemplatePlugins -> "Генератори шаблонів..."
    MenuSettingsTracking -> "Відстежувати використання застосунку..."
    MenuHelp -> "Довідка"
    MenuHelpCheckForUpdates -> "Перевірити наявність оновлень..."
    MenuHelpOpenLogDirectory -> "Відкрити каталог журналів"
    MenuHelpIncludeInfoLog -> "Увімкнути детальне журналювання"
    MenuHelpOpenHomePage -> "Відкрити домашню сторінку vLabeler"
    MenuHelpOpenLatestRelease -> "Відкрити останній випуск"
    MenuHelpOpenGitHub -> "Відкрити сторінку GitHub"
    MenuHelpJoinDiscord -> "Приєднатися до Discord"
    MenuHelpAbout -> "Про застосунок"
    CommonOkay -> "ОК"
    CommonApply -> "Застосувати"
    CommonCancel -> "Скасувати"
    CommonYes -> "Так"
    CommonNo -> "Ні"
    CommonWarning -> "Попередження"
    CommonError -> "Помилка"
    CommonDetails -> "Деталі"
    CommonOthers -> "Інші"
    CommonPrevious -> "Попередній"
    CommonNext -> "Наступний"
    CommonFinish -> "Готово"
    CommonSelect -> "Вибрати"
    CommonOpen -> "Відкрити"
    CommonSave -> "Зберегти"
    CommonReset -> "Скинути"
    CommonClear -> "Очистити"
    CommonInputErrorPromptNumber -> "Будь ласка, введіть число."
    CommonInputErrorPromptInteger -> "Будь ласка, введіть ціле число."
    CommonInputErrorPromptNumberRange -> "Будь ласка, введіть число між %s та %s."
    CommonInputErrorPromptNumberMin -> "Будь ласка, введіть число, більше або рівне %s."
    CommonInputErrorPromptNumberMax -> "Будь ласка, введіть число, менше або рівне %s."
    CommonRootModuleName -> "(Корінь)"
    StarterStart -> "Почати"
    StarterNewProject -> "Новий проєкт..."
    StarterOpen -> "Відкрити..."
    StarterQuickEdit -> "Швидке редагування"
    StarterRecent -> "Нещодавні"
    StarterRecentEmpty -> "У вас немає нещодавніх проєктів."
    StarterRecentDeleted -> "Цей файл проєкту було видалено."
    StarterNewSampleDirectory -> "Каталог семплів"
    StarterNewWorkingDirectory -> "Розташування проєкту"
    StarterNewProjectTitle -> "Новий проєкт"
    StarterNewProjectName -> "Назва проєкту"
    StarterNewProjectNameWarning -> "Файл проєкту вже існує. Створення проєкту перезапише його."
    StarterNewCacheDirectory -> "Каталог кешу"
    StarterNewLabelerCategory -> "Категорія"
    StarterNewLabeler -> "Міткувальник"
    StarterNewTemplatePlugin -> "Генератор шаблонів"
    StarterNewTemplatePluginNone -> "Немає"
    StarterNewInputFile -> "Вхідний файл (.%s)"
    StarterNewEncoding -> "Кодування"
    StarterNewAutoExport -> "Автоматичний експорт"
    StarterNewAutoExportHelp ->
        "Автоматично експортувати проєкт, перезаписуючи вказаний вхідний файл (якщо не вказано, " +
            "позиція файлу за замовчуванням визначається міткувальником) при збереженні проєкту."
    StarterNewWarningSelfConstructedLabelerWithTemplatePlugin ->
        "Ви намагаєтеся використати генератор шаблонів із міткувальником, який керує кількома підпроєктами. " +
            "Це небезпечно, оскільки може перезаписати всі ваші існуючі файли міток згенерованими записами. " +
            "Будь ласка, двічі переконайтеся, що налаштування відповідають вашим потребам."
    StarterNewDirectoryPage -> "Налаштування каталогів"
    StarterNewLabelerPage -> "Налаштування міткувальника"
    StarterNewDataSourcePage -> "Налаштування джерела даних"
    StarterNewContentType -> "Створити за допомогою..."
    StarterNewContentTypeDefault -> "За замовчуванням"
    StarterNewContentTypeFile -> "Файл"
    StarterNewContentTypePlugin -> "Генератор шаблонів"
    StarterNewAdvancedSettings -> "Додаткові налаштування"
    SampleListIncludedHeader -> "Файли семплів проєкту"
    SampleListIncludedItemEntryCountSingle -> "%d запис"
    SampleListIncludedItemEntryCountPlural -> "%d записів"
    SampleListExcludedHeader -> "Інші файли семплів"
    SampleListExcludedPlaceholder -> "У каталозі семплів немає незв'язаних файлів семплів."
    SampleListEntryHeader -> "Записи"
    SampleListEntriesPlaceholderUnselected -> "Виберіть файл семплу ліворуч, щоб показати прив'язані до нього записи."
    SampleListEntriesPlaceholderNoEntry -> "Немає записів, прив'язаних до вибраного файлу семплу."
    SampleListEntriesPlaceholderNoEntryButton -> "Створити за замовчуванням"
    SampleListCreateDefaultForAllButton -> "Створити за замовчуванням для всіх незв'язаних"
    SampleListJumpToSelectedEntryButton -> "Перейти до вибраного запису"
    SampleListOpenSampleDirectoryButton -> "Відкрити каталог семплів"
    SampleListCurrentModuleLabel -> "Підпроєкт: "
    SampleListSampleDirectoryLabel -> "Каталог семплів: "
    SampleListSampleDirectoryRedirectButton -> "Змінити каталог семплів"
    PrerendererModuleText -> "Рендеринг підпроєктів %d/%d..."
    PrerendererModuleTextFinished -> "Рендеринг підпроєктів %d/%d... Готово"
    PrerendererSampleText -> "Рендеринг файлів семплів %d/%d..."
    PrerendererSampleTextFinished -> "Рендеринг файлів семплів %d/%d... Готово"
    PrerendererChartText -> "Рендеринг графіків %d/%d..."
    PrerendererChartTextFinished -> "Рендеринг графіків %d/%d... Готово"
    EditorRenderStatusLabel -> "%d/%d Рендеринг..."
    ChooseSampleDirectoryDialogTitle -> "Вибрати каталог семплів"
    ChooseWorkingDirectoryDialogTitle -> "Вибрати розташування проєкту"
    ChooseCacheDirectoryDialogTitle -> "Вибрати каталог кешу"
    ChooseInputFileDialogTitle -> "Вибрати вхідний файл"
    OpenProjectDialogTitle -> "Відкрити проєкт"
    SaveAsProjectDialogTitle -> "Зберегти як проєкт"
    ImportDialogTitle -> "Імпорт"
    ExportDialogTitle -> "Експорт"
    SetResolutionDialogDescription -> "Введіть роздільну здатність полотна (точок на піксель) для редактора (%d ~ %d)"
    SetEntryPropertyDialogDescription ->
        "Будь ласка, введіть значення властивості `%s` цього запису. \n" +
            "Зверніть увагу, що ваше вхідне значення не буде обмежено, " +
            "тому, будь ласка, самостійно перевірте дійсність даних після цього процесу."
    AskIfSaveBeforeOpenDialogDescription ->
        "У вас є незбережені зміни. Бажаєте зберегти їх перед відкриттям " +
            "нового проєкту?"
    AskIfSaveBeforeExportDialogDescription -> "У вас є незбережені зміни. Бажаєте зберегти їх перед експортом?"
    AskIfSaveBeforeCloseDialogDescription ->
        "У вас є незбережені зміни. Бажаєте зберегти їх перед закриттям " +
            "поточного проєкту?"
    AskIfSaveBeforeExitDialogDescription -> "У вас є незбережені зміни. Бажаєте зберегти їх перед виходом?"
    InputEntryNameDialogDescription -> "Перейменувати запис"
    InputEntryNameDuplicateDialogDescription -> "Введіть назву для нового запису"
    InputEntryNameCutFormerDialogDescription -> "Введіть назву для попереднього запису після розрізання"
    InputEntryNameCutLatterDialogDescription -> "Введіть назву для наступного запису після розрізання"
    EditEntryNameDialogExistingError -> "Введена вами назва вже існує."
    EditEntryExtraDialogDescription -> "Редагувати додаткову інформацію поточного запису"
    EditModuleExtraDialogDescription -> "Редагувати додаткову інформацію поточного підпроєкту"
    MoveEntryDialogDescription -> "Введіть новий індекс для запису \"%1\$s\" (%2\$d ~ %3\$d)"
    AskIfRemoveEntryDialogDescription -> "Видалення запису \"%s\"..."
    AskIfRemoveEntryLastDialogDescription ->
        "Видалення запису \"%s\"...\n" +
            "Цей запис є єдиним, що посилається на поточний файл семплу.\n" +
            "Якщо вам потрібно буде додати на нього запис пізніше, перегляньте меню `Вигляд` -> `Список семплів`."
    AskIfLoadAutoSavedProjectDialogDescription ->
        "Знайдено файл проєкту, збережений автоматично. Бажаєте його завантажити? " +
            "Файл буде відкинуто, якщо ви відкриєте або створите інший."
    AskIfRedirectSampleDirectoryDialogDescription ->
        "Каталог семплів поточного підпроєкту (%s) не знайдено, " +
            "або він не містить жодного необхідного файлу семплу." +
            "Бажаєте перенаправити його до нового каталогу?"
    AskIfLabelFileChangeDetectedDialogDescription ->
        "Файл міток був змінений зовнішньою програмою. " +
            "Бажаєте перезавантажити файл, щоб відобразити зміни?\n" +
            "Ви можете налаштувати цю поведінку в `Параметри` -> `Автоматичне перезавантаження`."
    PluginDialogTitle -> "vLabeler - Плагін"
    PluginDialogInfoAuthor -> "автор: %s"
    PluginDialogInfoVersion -> "версія: %d"
    PluginDialogInfoContact -> "Зв'язатися з автором"
    PluginDialogDescriptionMin -> "мін: %s"
    PluginDialogDescriptionMax -> "макс: %s"
    PluginDialogDescriptionMinMax -> "мін: %s, макс: %s"
    PluginDialogExecute -> "Виконати"
    PluginDialogImportFromSavedParams -> "Завантажити збережені параметри за замовчуванням"
    PluginDialogImportFromSlot -> "Завантажити зі слоту %1\$d: %2\$s"
    PluginDialogEmptySlotName -> "(порожній)"
    PluginDialogImportFromFile -> "Імпортувати з файлу"
    PluginDialogImportSuccess -> "Налаштування успішно імпортовано."
    PluginDialogImportFailure -> "Не вдалося імпортувати налаштування. Ймовірно, вони несумісні з поточним елементом."
    PluginDialogExportToSavedParams -> "Зберегти параметри як стандартні"
    PluginDialogExportToSlot -> "Зберегти параметри до слоту %1\$d: %2\$s"
    PluginDialogExportToFile -> "Експортувати параметри до файлу"
    PluginDialogExportSuccess -> "Налаштування успішно експортовано."
    PluginDialogExportFailure -> "Не вдалося експортувати налаштування."
    PluginEntrySelectorTextMatchTypeEquals -> "Дорівнює"
    PluginEntrySelectorTextMatchTypeContains -> "Містить"
    PluginEntrySelectorTextMatchTypeStartsWith -> "Починається з"
    PluginEntrySelectorTextMatchTypeEndsWith -> "Закінчується на"
    PluginEntrySelectorTextMatchTypeRegex -> "Регулярний вираз"
    PluginEntrySelectorNumberMatchTypeEquals -> "="
    PluginEntrySelectorNumberMatchTypeGreaterThan -> ">"
    PluginEntrySelectorNumberMatchTypeGreaterThanOrEquals -> ">="
    PluginEntrySelectorNumberMatchTypeLessThan -> "<"
    PluginEntrySelectorNumberMatchTypeLessThanOrEquals -> "<="
    PluginEntrySelectorPreservedSubjectSample -> "Назва семплу (без розширення)"
    PluginEntrySelectorPreservedSubjectName -> "Назва запису"
    PluginEntrySelectorPreservedSubjectTag -> "Тег"
    PluginEntrySelectorPreservedSubjectDone -> "Готово"
    PluginEntrySelectorPreservedSubjectStar -> "Вибране"
    PluginEntrySelectorPreservedSubjectScript -> "Вираз"
    PluginEntrySelectorComparerValue -> "Введення"
    PluginEntrySelectorPreviewSummaryError -> "Неправильне введення"
    PluginEntrySelectorPreviewSummaryInitializing -> "Ініціалізація..."
    PluginEntrySelectorPreviewSummary -> "Вибрано %d/%d"
    PluginEntrySelectorPlaceholder -> "Фільтрів немає, вибрано всі записи."
    PluginEntrySelectorExpressionTitle -> "Вираз"
    PluginEntrySelectorExpressionDescription ->
        "Логічний вираз для об'єднання налаштованих вище фільтрів.\n" +
            "Доступні токени: `and`, `or`, `not`, `xor`, `(`, `)`, `#1`, `#2` тощо."
    EditorSubTitleMultiple -> "редагування %1\$d записів у семплі %2\$s"
    FailedToLoadSampleFileError -> "Не вдалося завантажити файл семплу.\nМожливо, він не існує або має непідтримуваний формат."
    PluginRuntimeUnexpectedException ->
        "Під час виконання плагіна сталася несподівана помилка.\n" +
            "Для отримання додаткової інформації зверніться до автора, надавши журнал помилок."
    FailedToCreateProjectException ->
        "Не вдалося створити проєкт." +
            "Будь ласка, перевірте налаштування міткувальника/плагіна, щоб переконатися, що ви налаштували його правильно.\n" +
            "Якщо проблема не зникає, зверніться до автора міткувальника/плагіна, надавши журнал помилок, " +
            "для отримання додаткової інформації."
    InvalidCreatedProjectException ->
        "Створений проєкт недійсний. " +
            "Будь ласка, перевірте налаштування міткувальника/плагіна, щоб переконатися, що ви налаштували його правильно.\n" +
            "Якщо проблема не зникає, зверніться до автора міткувальника/плагіна, надавши журнал помилок, " +
            "для отримання додаткової інформації."
    FailedToCreateProjectNoSampleException ->
        "Не вдалося створити проєкт, оскільки не знайдено жодного файлу семплу в каталозі семплів, встановленому в Налаштуваннях каталогів."
    InvalidOpenedProjectException ->
        "Не вдалося відкрити проєкт, оскільки він містить недійсні дані.\n" +
            "Будь ласка, перевірте журнал помилок для отримання додаткової інформації."
    ProjectParseException ->
        "Не вдалося відкрити проєкт.\n" +
            "Можливо, він пошкоджений або створений несумісною версією vLabeler.\n" +
            "Спробуйте створити новий проєкт та імпортувати файл проєкту, використовуючи меню `Файл` -> `Імпорт...`."
    ProjectImportException ->
        "Не вдалося імпортувати файл.\n" +
            "Можливо, це недійсний файл проєкту vLabeler. Будь ласка, перевірте журнал помилок для отримання додаткової інформації."
    ProjectUpdateOnSampleException ->
        "Не вдалося оновити проєкт за допомогою завантаженого файлу семплу." +
            "\nБудь ласка, перевірте журнал помилок для отримання додаткової інформації."
    InvalidEditedProjectException -> "Недійсний відредагований проєкт.\nБудь ласка, перевірте журнал помилок для отримання додаткової інформації."
    CustomizableItemLoadingException -> "Не вдалося завантажити вибраний налаштовуваний елемент."
    CustomizableItemRemovingException -> "Не вдалося видалити вибраний налаштовуваний елемент."
    PluginRuntimeExceptionTemplate -> "Помилка виконання плагіна: %s"
    ProjectConstructorRuntimeExceptionTemplate -> "Помилка виконання міткувальника під час створення проєкту: %s"
    QuickProjectBuilderRuntimeExceptionTemplate -> "Помилка виконання міткувальника під час створення проєкту для швидкого редагування: %s"
    PropertySetterRuntimeExceptionTemplate -> "Помилка виконання міткувальника під час встановлення властивості: %s"
    PropertySetterUnexpectedRuntimeException ->
        "Під час встановлення властивості сталася несподівана помилка.\n" +
            "Для отримання додаткової інформації зверніться до автора міткувальника, надавши журнал помилок."
    VideoComponentInitializationException ->
        "Не вдалося ініціалізувати відеокомпонент. Для використання цієї функції необхідно встановити VLC на вашому пристрої. " +
            "Будь ласка, перегляньте розділ `Інтеграція відео` у файлі README для отримання деталей."
    VideoFileNotFoundExceptionTemplate ->
        "Відео не знайдено з такою ж назвою \"%s\" та розширенням серед %s."
    LabelerManagerTitle -> "Міткувальники"
    LabelerManagerImportDialogTitle -> "Імпортувати міткувальник"
    TemplatePluginManagerTitle -> "Генератори шаблонів"
    TemplatePluginManagerImportDialogTitle -> "Імпортувати генератор шаблонів"
    MacroPluginManagerTitle -> "Плагіни пакетного редагування"
    MacroPluginManagerImportDialogTitle -> "Імпортувати плагін пакетного редагування"
    MacroPluginReportDialogTitle -> "Результат виконання пакетного редагування"
    MacroPluginReportDialogCopy -> "Копіювати"
    CustomizableItemManagerRemoveItemConfirm ->
        "Ви впевнені, що хочете видалити \"%s\"? " +
            "Це призведе до видалення файлу(ів) з диска."
    CustomizableItemManagerOpenDirectory -> "Відкрити каталог"
    CustomizableItemManagerReload -> "Перезавантажити список"
    CustomizableItemManagerLockedDescription -> "Цей елемент є вбудованим і не може бути видалений."
    PreferencesEditorImport -> "Імпорт"
    PreferencesEditorImportDialogTitle -> "Імпортувати параметри"
    PreferencesEditorImportSuccess -> "Параметри успішно імпортовано."
    PreferencesEditorImportFailure -> "Не вдалося імпортувати вибраний файл параметрів."
    PreferencesEditorExport -> "Експорт"
    PreferencesEditorExportSuccess -> "Параметри успішно експортовано."
    PreferencesEditorExportFailure -> "Не вдалося експортувати параметри до вибраного файлу."
    PreferencesEditorExportDialogTitle -> "Експорт параметрів"
    PreferencesEditorResetPage -> "Скинути елементи на цій сторінці"
    PreferencesEditorResetAll -> "Скинути всі елементи"
    PreferencesCharts -> "Графіки"
    PreferencesChartsDescription -> "Налаштування графіків, що відображаються в редакторі."
    PreferencesChartsCanvas -> "Полотно"
    PreferencesChartsCanvasDescription -> "Налаштування загальних параметрів полотна, на якому малюються графіки."
    PreferencesChartsCanvasResolution -> "Роздільна здатність полотна"
    PreferencesChartsCanvasResolutionDescription ->
        "Визначається як кількість точок семплу, включених в 1 піксель.\n" +
            "Чим більше число, тим довший проміжок часу відображається на екрані."
    PreferencesChartsCanvasResolutionDefault -> "Роздільна здатність за замовчуванням"
    PreferencesChartsCanvasResolutionStep -> "Крок"
    PreferencesChartsMaxDataChunkSize -> "Максимальний розмір фрагмента даних"
    PreferencesChartsMaxDataChunkSizeDescription ->
        "Максимальна кількість кадрів, яка буде включена у фрагмент графіка.\n" +
            "Чим більше число, тим менше частин будуть розділені ваші графіки під час рендерингу."
    PreferencesChartsWaveform -> "Форма хвилі"
    PreferencesChartsWaveformDescription -> "Налаштування графіка форми хвилі."
    PreferencesChartsWaveformResampleDownTo -> "Максимальна частота дискретизації (Гц)"
    PreferencesChartsWaveformResampleDownToDescription ->
        "Аудіофайл з вищою частотою дискретизації " +
            "буде передискретизований до заданого значення (файли не редагуються.)\n" +
            "Встановіть 0, щоб вимкнути передискретизацію."
    PreferencesChartsWaveformNormalize -> "Нормалізувати аудіо"
    PreferencesChartsWaveformNormalizeDescription ->
        "Нормалізація займає додатковий час при першому завантаженні семплів.\n" +
            "Аудіофайли не редагуються під час нормалізації."
    PreferencesChartsWaveformUnitSize -> "Точок на піксель"
    PreferencesChartsWaveformUnitSizeDescription -> "Збільште для нижчої якості зображення."
    PreferencesChartsWaveformIntensityAccuracy -> "Висота растрового зображення (пікс.)"
    PreferencesChartsWaveformYAxisBlankRate -> "Вертикальний відступ (%%)"
    PreferencesChartsWaveformColor -> "Колір"
    PreferencesChartsWaveformBackgroundColor -> "Колір фону"
    PreferencesChartsSpectrogram -> "Спектрограма"
    PreferencesChartsSpectrogramDescription -> "Налаштування графіка спектрограми."
    PreferencesChartsSpectrogramEnabled -> "Показати спектрограму"
    PreferencesChartsSpectrogramHeight -> "Висота відносно форми хвилі (%%)"
    PreferencesChartsSpectrogramPointDensity -> "Точок на піксель"
    PreferencesChartsSpectrogramPointDensityDescription -> "Збільште для нижчої якості зображення."
    PreferencesChartsSpectrogramHopSize -> "Розмір кроку ШПФ"
    PreferencesChartsSpectrogramHopSizeDescription -> "Адаптується до фактичної частоти дискретизації."
    PreferencesChartsSpectrogramWindowSize -> "Розмір вікна"
    PreferencesChartsSpectrogramWindowSizeDescription -> "Адаптується до фактичної частоти дискретизації."
    PreferencesChartsSpectrogramMelScaleStep -> "Роздільна здатність частоти (мел)"
    PreferencesChartsSpectrogramMaxFrequency -> "Максимальна відображувана частота (Гц)"
    PreferencesChartsSpectrogramMinIntensity -> "Мінімальна відображувана інтенсивність (дБ)"
    PreferencesChartsSpectrogramMinIntensityInvalid -> "Мінімальна інтенсивність повинна бути меншою за максимальну інтенсивність."
    PreferencesChartsSpectrogramMaxIntensity -> "Максимальна відображувана інтенсивність (дБ)"
    PreferencesChartsSpectrogramMaxIntensityInvalid -> "Максимальна інтенсивність повинна бути більшою за мінімальну інтенсивність."
    PreferencesChartsSpectrogramWindowType -> "Віконна функція"
    PreferencesChartsSpectrogramColorPalette -> "Кольори"
    PreferencesChartsSpectrogramColorPaletteDescription ->
        "Палітра кольорів для спектрограми. Ви можете додати власні палітри кольорів у @edit{цю папку}. " +
            "Щоб перезавантажити зміни, потрібно знову відкрити діалогове вікно параметрів."
    PreferencesChartsSpectrogramUseHighAlphaContrast -> "Використовувати високий альфа-контраст"
    PreferencesChartsSpectrogramUseHighAlphaContrastDescription ->
        "Ця опція впливає лише на колірні палітри, які мають альфа-значення."
    PreferencesChartsPower -> "Потужність"
    PreferencesChartsPowerDescription -> "Налаштування графіка потужності."
    PreferencesChartsPowerEnabled -> "Показати графік потужності"
    PreferencesChartsPowerMergeChannels -> "Об'єднати канали"
    PreferencesChartsPowerHeight -> "Висота відносно форми хвилі (%%)"
    PreferencesChartsPowerUnitSize -> "Точок на піксель"
    PreferencesChartsPowerUnitSizeDescription -> "Збільште для нижчої якості зображення."
    PreferencesChartsPowerUnitSizeInvalid -> "Розмір одиниці повинен бути меншим або дорівнювати Розміру вікна."
    PreferencesChartsPowerWindowSize -> "Розмір вікна"
    PreferencesChartsPowerWindowSizeInvalid -> "Розмір вікна повинен бути більшим або дорівнювати Розміру одиниці."
    PreferencesChartsPowerMinPower -> "Мінімальна відображувана потужність (дБ)"
    PreferencesChartsPowerMinPowerInvalid -> "Мінімальна потужність повинна бути меншою за максимальну потужність."
    PreferencesChartsPowerMaxPower -> "Максимальна відображувана потужність (дБ)"
    PreferencesChartsPowerMaxPowerInvalid -> "Максимальна потужність повинна бути більшою за мінімальну потужність."
    PreferencesChartsPowerIntensityAccuracy -> "Висота растрового зображення (пікс.)"
    PreferencesChartsPowerColor -> "Колір"
    PreferencesChartsPowerBackgroundColor -> "Колір фону"
    PreferencesChartsFundamental -> "F0"
    PreferencesChartsFundamentalDescription -> "Налаштування графіка F0."
    PreferencesChartsFundamentalEnabled -> "Показати графік F0"
    PreferencesChartsFundamentalHeight -> "Висота відносно форми хвилі (%%)"
    PreferencesChartsFundamentalSemitoneResolution -> "Роздільна здатність півтонів у зображенні"
    PreferencesChartsFundamentalMinFundamental -> "Мінімальна відображувана частота (Гц)"
    PreferencesChartsFundamentalMinFundamentalInvalid -> "Мінімальна частота повинна бути меншою за максимальну частоту."
    PreferencesChartsFundamentalMaxFundamental -> "Максимальна відображувана частота (Гц)"
    PreferencesChartsFundamentalMaxFundamentalInvalid -> "Максимальна частота повинна бути більшою за мінімальну частоту."
    PreferencesChartsFundamentalSemitoneSampleNum -> "Кількість семплів для кожного півтону"
    PreferencesChartsFundamentalMaxHarmonicFrequency -> "Максимальна гармонічна частота (Гц)"
    PreferencesChartsFundamentalMaxHarmonicFrequencyInvalid ->
        "Максимальна гармонічна частота повинна бути більшою за максимальну частоту."
    PreferencesChartsFundamentalDrawReferenceLine -> "Малювати опорні лінії на клавішах C"
    PreferencesChartsFundamentalColor -> "Колір"
    PreferencesChartsFundamentalReferenceLineColor -> "Колір опорної лінії"
    PreferencesChartsFundamentalBackgroundColor -> "Колір фону"
    PreferencesChartsConversion -> "Підтримка аудіоформатів"
    PreferencesChartsConversionDescription -> "Налаштування підтримки аудіоформатів, відмінних від wav."
    PreferencesChartsConversionFFmpegPath -> "Шлях до виконуваного файлу FFmpeg"
    PreferencesChartsConversionFFmpegPathDescription ->
        "Будь ласка, встановіть @open{FFmpeg} та вкажіть шлях до виконуваного файлу, " +
            "щоб виконувати перетворення форматів перед завантаженням. " +
            "Вам також може знадобитися переконатися, що ваша ОС дозволяє виконання цього файлу перед використанням у vLabeler. " +
            "Можливі помилки можуть бути пов'язані з непідписаними виконуваними файлами або дозволами доступу."
    PreferencesChartsConversionFFmpegArgs -> "Аргументи FFmpeg, окрім вхідного та вихідного файлів"
    PreferencesChartsConversionFFmpegUseForWav -> "Використовувати перетворення FFmpeg для файлів wav"
    PreferencesKeymap -> "Призначення клавіш"
    PreferencesKeymapDescription -> "Налаштування прив'язок клавіш для дій клавіатури/миші."
    PreferencesKeymapKeyAction -> "Дії клавіш"
    PreferencesKeymapKeyActionDescription -> "Налаштування прив'язок клавіш для дій клавіатури."
    PreferencesKeymapMouseClickAction -> "Дії миші при кліку"
    PreferencesKeymapMouseClickActionDescription ->
        "Налаштування клавіатурних прив'язок для дій миші при кліку.\n" +
            "Дія виконується лише тоді, коли натиснуті всі клавіші, вказані у прив'язці."
    PreferencesKeymapMouseScrollAction -> "Дії миші при прокручуванні"
    PreferencesKeymapMouseScrollActionDescription ->
        "Налаштування клавіатурних прив'язок для дій миші при прокручуванні.\n" +
            "Дія виконується лише тоді, коли натиснуті всі клавіші, вказані у прив'язці."
    PreferencesKeymapEditDialogTitle -> "Редагування клавіатурної прив'язки для:"
    PreferencesKeymapEditDialogDescriptionMouseClick ->
        "Клацніть лівою/правою кнопкою миші на текстовому полі, " +
            "утримуючи інші клавіші, щоб ввести швидкий доступ."
    PreferencesKeymapEditDialogDescriptionMouseScroll ->
        "Прокрутіть коліщатко миші на текстовому полі, " +
            "утримуючи інші клавіші, щоб ввести швидкий доступ."
    PreferencesKeymapEditDialogConflictingLabel -> "Вже призначено для:"
    PreferencesKeymapEditDialogConflictingWarning ->
        "Цей швидкий доступ вже призначено іншим діям.\n" +
            "Ви бажаєте видалити інші призначення?"
    PreferencesKeymapEditDialogConflictingWarningKeep -> "Залишити"
    PreferencesKeymapEditDialogConflictingWarningRemove -> "Видалити"
    PreferencesView -> "Вигляд"
    PreferencesViewDescription -> "Налаштування зовнішнього вигляду"
    PreferencesViewLanguage -> "Мова"
    PreferencesViewFontFamily -> "Шрифт"
    PreferencesViewFontFamilyDescription ->
        "Шрифт (гарнітура), що використовується в застосунку.\n" +
            "Окрім наявних варіантів, ви можете додати шрифти до @edit{цієї папки}. " +
            "Наразі шрифти ttc не повністю підтримуються. " +
            "Щоб використовувати всі стилі шрифту ttc, будь ласка, конвертуйте його до файлів ttf/otf заздалегідь.\n" +
            "Вам потрібно буде знову відкрити діалогове вікно налаштувань, щоб перезавантажити додані шрифти."
    PreferencesViewHideSampleExtension -> "Приховати розширення файлу зразка"
    PreferencesViewAppAccentColor -> "Колір акценту застосунку (світлий)"
    PreferencesViewAppAccentColorVariant -> "Колір акценту застосунку (темний)"
    PreferencesViewPinnedEntryListPosition -> "Позиція списку закріплених записів"
    PreferencesViewPositionLeft -> "Зліва"
    PreferencesViewPositionRight -> "Справа"
    PreferencesViewPositionTop -> "Згори"
    PreferencesViewPositionBottom -> "Знизу"
    PreferencesViewCornerPositionTopLeft -> "Вгорі ліворуч"
    PreferencesViewCornerPositionTopRight -> "Вгорі праворуч"
    PreferencesViewCornerPositionCenterLeft -> "По центру ліворуч"
    PreferencesViewCornerPositionCenterRight -> "По центру праворуч"
    PreferencesViewCornerPositionBottomLeft -> "Внизу ліворуч"
    PreferencesViewCornerPositionBottomRight -> "Внизу праворуч"
    PreferencesFontSizeSmall -> "Малий"
    PreferencesFontSizeMedium -> "Середній"
    PreferencesFontSizeLarge -> "Великий"
    PreferencesFontSizeExtraLarge -> "Дуже великий"
    PreferencesEditor -> "Редактор"
    PreferencesEditorDescription -> "Налаштування вигляду та поведінки редактора."
    PreferencesEditorPlayerCursorColor -> "Колір курсору програвача"
    PreferencesEditorLockedDrag -> "Фіксоване перетягування"
    PreferencesEditorLockedDragDescription ->
        "Оберіть умову для ввімкнення фіксованого перетягування під час переміщення " +
            "ліній параметрів.\n" +
            "Коли воно ввімкнене, інші лінії параметрів будуть переміщуватися відповідно, щоб " +
            "зберігати відносні позиції до параметра, який ви переміщуєте."
    PreferencesEditorLockedDragUseLabeler -> "Використовувати налаштування, визначені розмітником"
    PreferencesEditorLockedDragUseStart -> "Фіксоване перетягування на початку запису"
    PreferencesEditorLockedDragNever -> "Ніколи не використовувати фіксоване перетягування"
    PreferencesEditorLockedSettingParameterWithCursor -> "Застосовувати фіксоване перетягування з налаштуванням курсору"
    PreferencesEditorLockedSettingParameterWithCursorDescription ->
        "Застосовувати налаштування фіксованого перетягування вище також, коли " +
            "встановлюєте параметри за допомогою клавішних дій \"Встановити параметр на позицію курсору\""
    PreferencesEditorNotes -> "Примітки"
    PreferencesEditorNotesDescription ->
        "Налаштування вигляду та поведінки редактора щодо " +
            "приміток до запису (позначений зірочкою, виконаний, тег, додаткова інформація)."
    PreferencesEditorShowDone -> "Показувати статус \"Виконано\""
    PreferencesEditorShowStarred -> "Показувати статус \"Позначено зірочкою\""
    PreferencesEditorShowTag -> "Показувати теги"
    PreferencesEditorShowExtra -> "Показувати \"Редагувати додаткову інформацію\""
    PreferencesEditorShowExtraDescription ->
        "Навіть якщо ввімкнено, якщо розмітник не визначає додаткової інформації, кнопка не буде показана."
    PreferencesEditorPostEditAction -> "Дії після редагування"
    PreferencesEditorPostEditActionDescription -> "Визначення дій, які будуть виконуватися після редагування запису."
    PreferencesEditorPostEditActionDone -> "Позначати відредаговані записи як \"Виконано\" після редагування"
    PreferencesEditorPostEditActionNext -> "Переходити до наступного запису після редагування"
    PreferencesEditorPostEditActionEnabled -> "Увімкнено"
    PreferencesEditorPostEditActionTrigger -> "Параметр(и) для запуску дії"
    PreferencesEditorPostEditActionTriggerUseLabeler -> "Використовувати налаштування, визначені розмітником"
    PreferencesEditorPostEditActionTriggerUseStart -> "Початок запису"
    PreferencesEditorPostEditActionTriggerUseEnd -> "Кінець запису"
    PreferencesEditorPostEditActionTriggerUseAny -> "Будь-який параметр"
    PreferencesEditorPostEditActionUseDragging -> "Запускати при перетягуванні"
    PreferencesEditorPostEditActionUseDraggingDescription -> "Запускати дію після перетягування ліній(ї) параметрів."
    PreferencesEditorPostEditActionUseCursorSet -> "Запускати при \"Встановити параметр на позицію курсору\""
    PreferencesEditorPostEditActionUseCursorSetDescription ->
        "Запускати дію після встановлення параметра(ів) за допомогою клавішних дій \"Встановити параметр на позицію курсору\"."
    PreferencesEditorScissors -> "Ножиці"
    PreferencesEditorScissorsDescription -> "Налаштування вигляду та поведінки інструменту \"Ножиці\"."
    PreferencesEditorScissorsUseOnScreenScissors -> "Вводити назви записів безпосередньо в редакторі"
    PreferencesEditorScissorsUseOnScreenScissorsDescription ->
        "Коли ввімкнено, після натискання інструментом \"Ножиці\" в редакторі відображається поле введення для імені нового запису. Ви можете підтвердити дію розрізання, натиснувши Enter або перемістивши курсор подалі від позиції клацання. Ви також можете скасувати дію, натиснувши Esc. Це доступно лише в режимі множинного редагування."
    PreferencesEditorScissorsScissorsSubmitThreshold -> "Поріг підтвердження дії (DP)"
    PreferencesEditorScissorsScissorsSubmitThresholdDescription ->
        "Після клацання ножицями, коли ви переміщуєте курсор від позиції клацання і відстань " +
            "перевищує поріг, дія розрізання буде підтверджена."
    PreferencesEditorScissorsColor -> "Колір"
    PreferencesEditorScissorsActionTargetNone -> "Нічого"
    PreferencesEditorScissorsActionTargetFormer -> "Попередній запис"
    PreferencesEditorScissorsActionTargetLatter -> "Наступний запис"
    PreferencesEditorScissorsActionGoTo -> "Перейти до запису після розрізання"
    PreferencesEditorScissorsActionAskForName -> "Перейменувати запис після розрізання"
    PreferencesEditorScissorsActionPlay -> "Відтворити аудіо під час розрізання"
    PreferencesEditorAutoScroll -> "Автопрокрутка"
    PreferencesEditorAutoScrollDescription ->
        "Визначення, коли редактор буде автоматично прокручуватися, щоб показати " +
            "поточний запис."
    PreferencesEditorAutoScrollOnLoadedNewSample -> "При перемиканні на інший зразок"
    PreferencesEditorAutoScrollOnJumpedToEntry -> "При переході до іншого запису за абсолютним індексом"
    PreferencesEditorAutoScrollOnSwitchedInMultipleEditMode -> "При перемиканні на інший запис у режимі множинного редагування"
    PreferencesEditorAutoScrollOnSwitched -> "При перемиканні на інший запис"
    PreferencesEditorContinuousLabelNames -> "Назви розміток (безперервний)"
    PreferencesEditorContinuousLabelNamesDescription ->
        "Налаштування вигляду тексту назв записів, що відображаються в редакторі, при використанні безперервного розмітника."
    PreferencesEditorContinuousLabelNamesColor -> "Колір"
    PreferencesEditorContinuousLabelNamesBackgroundColor -> "Колір тла"
    PreferencesEditorContinuousLabelNamesEditableBackgroundColor -> "Колір тла (редагування)"
    PreferencesEditorContinuousLabelNamesSize -> "Розмір"
    PreferencesEditorContinuousLabelNamesPosition -> "Позиція"
    PreferencesEditorBorderHighlight -> "Підсвічування рамки"
    PreferencesEditorBorderHighlightDescription -> "Налаштування підсвічування рамки в режимі множинного редагування."
    PreferencesEditorHighlightCurrentEntryBorder -> "Підсвічувати рамки поточного запису"
    PreferencesEditorHighlightCurrentEntryBorderDescription -> "У режимі множинного редагування підсвічувати рамки запису, який наразі вибраний у списку записів."
    PreferencesEditorHighlightCursorPositionEntryBorder -> "Підсвічувати рамки запису з позицією курсору"
    PreferencesEditorHighlightCursorPositionEntryBorderDescription -> "У режимі множинного редагування підсвічувати рамки запису, де наразі знаходиться ваш курсор."
    PreferencesEditorHighlightEntryBorderEnabled -> "Увімкнено"
    PreferencesEditorHighlightEntryBorderColor -> "Колір"
    PreferencesEditorHighlightEntryBorderWidth -> "Ширина"
    PreferencesPlayback -> "Відтворення"
    PreferencesPlaybackDescription -> "Налаштування поведінки відтворення аудіо."
    PreferencesPlaybackPlayOnDragging -> "Попереднє відтворення"
    PreferencesPlaybackPlayOnDraggingDescription ->
        "При перетягуванні будь-яких ліній параметрів за допомогою клавіш для \"Попереднього відтворення\" (див. клавіатурні прив'язки), " +
            "відтворювати аудіодіапазон поблизу курсору."
    PreferencesPlaybackPlayOnDraggingEnabled -> "Увімкнено"
    PreferencesPlaybackPlayOnDraggingRangeRadiusMillis -> "Радіус (мс)"
    PreferencesPlaybackPlayOnDraggingEventQueueSize -> "Зберігати події перетягування"
    PreferencesAutoSave -> "Автозбереження"
    PreferencesAutoSaveDescription -> "Налаштування поведінки автозбереження проєкту."
    PreferencesAutoSaveTarget -> "Місце розташування файлу автозбереження"
    PreferencesAutoSaveTargetNone -> "Не виконувати автозбереження"
    PreferencesAutoSaveTargetProject -> "Перезаписати файл проєкту"
    PreferencesAutoSaveTargetRecord -> "Зберегти до тимчасового файлу"
    PreferencesAutoSaveIntervalSec -> "Інтервал (сек)"
    PreferencesAutoReload -> "Автоперезавантаження"
    PreferencesAutoReloadDescription -> "Налаштування поведінки автоперезавантаження файлів розмітки при їх зміні."
    PreferencesAutoReloadBehavior -> "Поведінка"
    PreferencesAutoReloadBehaviorDisabled -> "Вимкнено"
    PreferencesAutoReloadBehaviorAskWithDetails -> "Запитати з деталями"
    PreferencesAutoReloadBehaviorAsk -> "Запитати Так/Ні"
    PreferencesAutoReloadBehaviorAuto -> "Автоматично"
    PreferencesHistory -> "Історія редагування"
    PreferencesHistoryDescription -> "Налаштування поведінки історії редагування (скасувати/повторити)."
    PreferencesHistoryMaxSize -> "Максимальний розмір збереження"
    PreferencesHistorySquashIndex -> "Стискати зміни індексу"
    PreferencesHistorySquashIndexDescription ->
        "Коли ввімкнено, зміни індексу (наприклад, перемикання записів) не будуть збережені " +
            "до наступної зміни вмісту."
    PreferencesMisc -> "Різне"
    PreferencesMiscDescription -> "Налаштування іншої поведінки. Зверніть увагу, що ці налаштування можуть бути експериментальними."
    PreferencesMiscUpdateChannel -> "Канал оновлень"
    PreferencesMiscUpdateChannelDescription ->
        "Канал оновлень, що використовується при автоматичній перевірці оновлень або в меню `Довідка` -> `Перевірити оновлення...`."
    UpdateChannelStable -> "Стабільний"
    UpdateChannelPreview -> "Попередній перегляд"
    PreferencesMiscUseCustomFileDialog -> "Використовувати власні діалогові вікна файлів замість системних"
    PreferencesMiscUseCustomFileDialogDescription ->
        "Коли ввімкнено, діалогові вікна файлів будуть замінені власними. " +
            "Це може бути корисно, якщо ви використовуєте робоче середовище, яке не підтримує " +
            "системні діалогові вікна файлів. Можливо, вам знадобиться перезапустити застосунок, щоб застосувати це налаштування."
    PreferencesMiscDangerZone -> "Небезпечна зона"
    PreferencesMiscClearRecord -> "Очистити історію використання застосунку"
    PreferencesMiscClearRecordDescription ->
        "Видалити всі дані про використання застосунку, які не керуються налаштуваннями, " +
            "такі як розміри вікон, пропущені версії оновлень, збережені налаштування слотів плагінів тощо."
    PreferencesMiscClearRecordButton -> "Очистити"
    PreferencesMiscClearRecordConfirmation ->
        "Ви впевнені, що хочете очистити всі дані історії використання застосунку?\n" +
            "Цю дію не можна скасувати.\n" +
            "Застосунок негайно завершить роботу після очищення, без збереження поточного відкритого проєкту."
    PreferencesMiscClearAppData -> "Стерти всі дані застосунку"
    PreferencesMiscClearAppDataDescription ->
        "Видалити всі дані застосунку, включаючи налаштування, історію використання, встановлені плагіни тощо."
    PreferencesMiscClearAppDataButton -> "Стерти всі дані"
    PreferencesMiscClearAppDataConfirmation ->
        "Ви впевнені, що хочете стерти всі дані застосунку?\n" +
            "Цю дію не можна скасувати, і вона видалить усі дані, пов'язані з vLabeler, з вашого пристрою, " +
            "за винятком файлів, які ви явно створили, наприклад, файлів, пов'язаних з проєктом.\n" +
            "Застосунок негайно завершить роботу після стирання, без збереження поточного відкритого проєкту."
    ActionToggleSamplePlayback -> "Увімкнути/Вимкнути Відтворення Поточного Зразка"
    ActionToggleEntryPlayback -> "Увімкнути/Вимкнути Відтворення Поточного Запису"
    ActionToggleScreenRangePlayback -> "Увімкнути/Вимкнути Відтворення Поточного Діапазону Екрана"
    ActionToggleVideoPopupEmbedded -> "Увімкнути/Вимкнути Відео (Вбудоване)"
    ActionToggleVideoPopupNewWindow -> "Увімкнути/Вимкнути Відео (В Новому Вікні)"
    ActionIncreaseResolution -> "Зменшити Масштаб"
    ActionDecreaseResolution -> "Збільшити Масштаб"
    ActionInputResolution -> "Ввести Роздільну Здатність Полотна"
    ActionCancelDialog -> "Закрити Діалогове Вікно"
    ActionScissorsCut -> "Розрізати на Позиції Поточного Курсору"
    ActionSetValue1 -> "Встановити Параметр 1 На Позицію Курсору"
    ActionSetValue2 -> "Встановити Параметр 2 На Позицію Курсору"
    ActionSetValue3 -> "Встановити Параметр 3 На Позицію Курсору"
    ActionSetValue4 -> "Встановити Параметр 4 На Позицію Курсору"
    ActionSetValue5 -> "Встановити Параметр 5 На Позицію Курсору"
    ActionSetValue6 -> "Встановити Параметр 6 На Позицію Курсору"
    ActionSetValue7 -> "Встановити Параметр 7 На Позицію Курсору"
    ActionSetValue8 -> "Встановити Параметр 8 На Позицію Курсору"
    ActionSetValue9 -> "Встановити Параметр 9 На Позицію Курсору"
    ActionSetValue10 -> "Встановити Параметр 10 На Позицію Курсору"
    ActionSetProperty1 -> "Ввести Значення для Властивості 1"
    ActionSetProperty2 -> "Ввести Значення для Властивості 2"
    ActionSetProperty3 -> "Ввести Значення для Властивості 3"
    ActionSetProperty4 -> "Ввести Значення для Властивості 4"
    ActionSetProperty5 -> "Ввести Значення для Властивості 5"
    ActionSetProperty6 -> "Ввести Значення для Властивості 6"
    ActionSetProperty7 -> "Ввести Значення для Властивості 7"
    ActionSetProperty8 -> "Ввести Значення для Властивості 8"
    ActionSetProperty9 -> "Ввести Значення для Властивості 9"
    ActionSetProperty10 -> "Ввести Значення для Властивості 10"
    ActionQuickLaunch1 -> "Запустити Слот Плагіна 1"
    ActionQuickLaunch2 -> "Запустити Слот Плагіна 2"
    ActionQuickLaunch3 -> "Запустити Слот Плагіна 3"
    ActionQuickLaunch4 -> "Запустити Слот Плагіна 4"
    ActionQuickLaunch5 -> "Запустити Слот Плагіна 5"
    ActionQuickLaunch6 -> "Запустити Слот Плагіна 6"
    ActionQuickLaunch7 -> "Запустити Слот Плагіна 7"
    ActionQuickLaunch8 -> "Запустити Слот Плагіна 8"
    ActionMoveParameter -> "Перетягнути Лінію Параметра"
    ActionMoveParameterWithPlaybackPreview -> "Перетягнути Лінію Параметра з Попереднім Відтворенням"
    ActionMoveParameterIgnoringConstraints -> "Перетягнути Лінію Параметра Ігноруючи Обмеження"
    ActionMoveParameterInvertingLocked -> "Перетягнути Лінію Параметра з Інвертованими Налаштуваннями Фіксованого Перетягування"
    ActionPlayAudioSection -> "Відтворити Клацнуту Частину Аудіо"
    ActionPlayAudioUntilEnd -> "Відтворити Аудіо від Клацнутої Позиції до Кінця"
    ActionPlayAudioUntilScreenEnd -> "Відтворити Аудіо від Клацнутої Позиції до Кінця Екрана"
    ActionPlayAudioFromStart -> "Відтворити Аудіо від Початку до Клацнутої Позиції"
    ActionPlayAudioFromScreenStart -> "Відтворити Аудіо від Початку Екрана до Клацнутої Позиції"
    ActionPlayAudioRange -> "Відтворити Аудіо у Перетягнутому Діапазоні"
    ActionPlayAudioRangeRepeat -> "Відтворити Аудіо у Перетягнутому Діапазоні Повторно"
    ActionScrollCanvasLeft -> "Прокрутити Полотно Ліворуч"
    ActionScrollCanvasRight -> "Прокрутити Полотно Праворуч"
    ActionZoomInCanvas -> "Збільшити Масштаб"
    ActionZoomOutCanvas -> "Зменшити Масштаб"
    ActionGoToNextEntry -> "Перейти до Наступного Запису"
    ActionGoToPreviousEntry -> "Перейти до Попереднього Запису"
    ActionGoToNextSample -> "Перейти до Наступного Зразка"
    ActionGoToPreviousSample -> "Перейти до Попереднього Зразка"
    CheckForUpdatesAlreadyUpdated -> "У вас вже встановлена остання версія vLabeler."
    CheckForUpdatesFailure -> "Не вдалося отримати інформацію про останню версію."
    UpdaterDialogSummaryDetailsLink -> "Деталі"
    UpdaterDialogTitle -> "vLabeler - Оновлення"
    UpdaterDialogCurrentVersionLabel -> "Поточна версія: %s"
    UpdaterDialogLatestVersionLabel -> "Остання версія: %1\$s (%2\$s)"
    UpdaterDialogStartDownloadButton -> "Завантажити"
    UpdaterDialogIgnoreButton -> "Ігнорувати цю версію"
    UpdaterDialogDownloadPositionLabel -> "Місце завантаження: "
    UpdaterDialogChangeDownloadPositionButton -> "Змінити"
    UpdaterDialogChooseDownloadPositionDialogTitle -> "Вибрати місце завантаження"
    AboutDialogTitle -> "vLabeler - Про застосунок"
    AboutDialogCopyInfo -> "Копіювати інформацію"
    AboutDialogShowLicenses -> "Показати ліцензії"
    LicenseDialogTitle -> "vLabeler - Ліцензії"
    LicenseDialogLicenses -> "Ліцензії OSS, використані у vLabeler"
    LoadProjectErrorLabelerNotFound ->
        "Неможливо знайти необхідний розмітник `%1\$s` (версія %2\$s) на цьому пристрої. " +
            "Будь ласка, встановіть його вручну, перш ніж відкривати проєкт."
    LoadProjectWarningLabelerCreated -> "Новий розмітник `%s` встановлено файлом проєкту."
    LoadProjectWarningLabelerUpdated -> "Розмітник `%s` оновлено до версії `%s` файлом проєкту."
    LoadProjectWarningCacheDirReset ->
        "Не вдалося знайти або створити каталог кешу, визначений у файлі проєкту. " +
            "Замість цього буде використано каталог кешу за замовчуванням."
    FilterStarred -> "Фільтрування позначених зірочкою записів"
    FilterUnstarred -> "Фільтрування не позначених зірочкою записів"
    FilterStarIgnored -> "Не фільтрується за зірочкою"
    FilterDone -> "Фільтрування виконаних записів"
    FilterUndone -> "Фільтрування невиконаних записів"
    FilterDoneIgnored -> "Не фільтрується за виконанням"
    FilterLink -> "Перемкнути, щоб застосувати фільтри до навігації по проєкту"
    FilterLinked -> "Фільтри застосовані до навігації по проєкту"
    FilterAdvancedInUse -> "Розширені Фільтри"
    FilterDisabledDueToAdvancedInUse -> "Вимкнено, оскільки застосовано розширені фільтри"
    ColorPickerDialogTitle -> "vLabeler - Вибір кольору"
    QuickLaunchManagerDialogTitle -> "Слоти Плагінів"
    QuickLaunchManagerDialogDescription ->
        "Ви можете встановити часто використовувані плагіни пакетного редагування з їхніми параметрами в слоти плагінів " +
            "для швидкого доступу. Параметри, що зберігаються у слотах плагінів, незалежні один від одного, " +
            "і не впливають на параметри, збережені при звичайному використанні."
    QuickLaunchManagerDialogHeaderTitle -> "Слот"
    QuickLaunchManagerDialogHeaderPlugin -> "Плагін"
    QuickLaunchManagerDialogHeaderForceAskParams -> "Завжди запитувати параметри"
    QuickLaunchManagerDialogItemTitle -> "Слот %d"
    QuickLaunchManagerDialogOpenKeymap -> "Відкрити клавіатурні прив'язки"
    TrackingSettingsDialogTitle -> "Відстеження Використання Застосунку"
    TrackingSettingsDialogDescription ->
        "Тут ви можете ввімкнути/вимкнути відстеження даних про використання, яке збирає анонімні події використання, такі як " +
            "`Запуск Застосунку` та `Використання Плагіна`. Зібрані дані використовуються для покращення vLabeler, " +
            "і вони не містять жодної конкретної інформації про ваш проєкт, дані або особисту інформацію. " +
            "Будь ласка, увімкніть відстеження, якщо вважаєте це прийнятним. " +
            "Ви можете переглянути більше деталей, натиснувши кнопку `Деталі`."
    TrackingSettingsDialogFirstTimeAlert ->
        "Ми показуємо вам це діалогове вікно, оскільки ви вперше використовуєте vLabeler з увімкненим відстеженням. " +
            "Ви можете відкрити це діалогове вікно та змінити налаштування відстеження в будь-який час у меню " +
            "`Налаштування` -> `Відстеження Використання Застосунку...`"
    TrackingSettingsDialogEnabled -> "Увімкнено"
    TrackingSettingsDialogTrackingIdLabel -> "ID відстеження:"
    ProjectSettingDialogTitle -> "Налаштування Проєкту"
    ProjectSettingOutputFileLabel -> "Вихідний файл"
    ProjectSettingOutputFileHelperText ->
        "Цільовий файл для дії `Експортувати`.\nЯкщо не встановлено, `Експорт з перезаписом` вимкнено."
    ProjectSettingOutputFileDisabledPlaceholder -> "Вимкнено поточним розмітником"
    ProjectSettingOutputFileSelectorDialogTitle -> "Вибрати вихідний файл"
    ProjectSettingAutoExportHelperText ->
        "Автоматично експортувати всі підпроєкти до їхніх вихідних файлів при збереженні проєкту.\n" +
            "Ця опція діє лише тоді, коли `Вихідний файл` встановлено належним чином,\n" +
            "або зафіксовано розмітником."
    ImportEntriesDialogTitle -> "Імпорт Проєкту"
    ImportEntriesDialogItemSummaryTitle -> "%d Записів"
    ImportEntriesDialogItemTargetLabel -> "Ціль"
    ImportEntriesDialogItemIncompatible -> "Несумісно з поточним проєктом"
    ImportEntriesDialogReplaceContent -> "Видалити поточні записи"
    ImportEntriesDialogReplaceContentDisabledDescription ->
        "Поточний проєкт не підтримує додавання записів, " +
            "тому всі поточні записи будуть видалені перед імпортом."
    EntrySampleSyncerModuleText -> "Обробка підпроєктів %d/%d..."
    EntrySampleSyncerModuleTextFinished -> "Обробка підпроєктів %d/%d... Виконано"
    EntrySampleSyncerSampleText -> "Обробка файлів зразків %d/%d..."
    EntrySampleSyncerSampleTextFinished -> "Обробка файлів зразків %d/%d... Виконано"
    FFmpegConverterException ->
        "Не вдалося завантажити файл зразка. Щоб завантажити формати, відмінні від wav, " +
            "будь ласка, встановіть FFmpeg і налаштуйте його шлях у `Налаштування` -> `Діаграми` -> `Підтримка аудіоформатів`. " +
            "Якщо ви вже встановили та налаштували FFmpeg, перевірте журнал для отримання додаткової інформації."
    AppRunningOnCompatibilityModeWarning ->
        "vLabeler працює в режимі сумісності Rosetta 2.\n" +
            "Для кращої продуктивності, будь ласка, спробуйте збірку для Apple Silicon (~mac-arm64.dmg)."
    EntryFilterSetterDialogTitle -> "Налаштування Фільтра"
    EntryFilterSetterDialogModeBasic -> "Базовий"
    EntryFilterSetterDialogModeAdvanced -> "Розширений"
    EntryFilterSetterDialogHeaderAny -> "Будь-який текст містить"
    EntryFilterSetterDialogHeaderName -> "Назва запису містить"
    EntryFilterSetterDialogHeaderSample -> "Назва зразка містить"
    EntryFilterSetterDialogHeaderTag -> "Тег містить"
    EntryFilterSetterDialogHeaderStar -> "Позначено зірочкою"
    EntryFilterSetterDialogHeaderDone -> "Виконано"
    FileNameNormalizerDialogTitle -> "vLabeler - Нормалізатор Імен Файлів"
    FileNameNormalizerTitle -> "Нормалізатор Імен Файлів"
    FileNameNormalizerDescription ->
        "Цей інструмент призначений для перетворення імен файлів з кодування NFD (зазвичай використовується в macOS) на " +
            "NFC (зазвичай використовується в Windows)." +
            "Виберіть папку для рекурсивного перетворення всіх імен файлів у ній, " +
            "або виберіть файл для перетворення його вмісту.\n" +
            "Якщо ви вже створили проєкт на основі файлів зразків, переконайтеся, що ви перетворюєте як імена файлів зразків, " +
            "так і вміст файлу проєкту."
    FileNameNormalizerHandleFolderButton -> "Вибрати папку"
    FileNameNormalizerHandleFileContentButton -> "Вибрати файл"
    FileNameNormalizerHandleFolderSuccess -> "Відскановано %d файлів, перетворено %d файлів."
    FileNameNormalizerHandleFileSuccess -> "Вміст файлу успішно перетворено."
    FileNameNormalizerHandleFileNoChange -> "Перетворення вмісту файлу не потрібне."
    ReloadLabelDialogTitle -> "Перезавантажити Файл Розмітки"
    ReloadLabelDialogModuleNameTemplate -> "Підпроєкт: %s"
    ReloadLabelDialogShowUnchanged -> "Показати без змін"
    ReloadLabelDialogNotice ->
        "Цей попередній перегляд різниці розрахований на основі налаштувань поточного розмітника, " +
            "тому він може не показувати всі незначні відмінності. Будь ласка, перевірте фактичний вміст після перезавантаження, щоб переконатися, " +
            "що все правильно."
    ReloadLabelDialogNoDiff -> "Різниць не знайдено."
    ReloadLabelDialogInheritNotes -> "Успадкувати примітки"
    ReloadLabelDialogInheritNotesDescription ->
        "Якщо ввімкнено, примітки на старих записах будуть скопійовані до нових записів для всіх відповідних пар записів."
    EditorContextActionOpenRenameEntryDialog -> "Перейменувати Запис..."
    EditorContextActionOpenDuplicateEntryDialog -> "Дублювати Запис..."
    EditorContextActionOpenRemoveEntryDialog -> "Видалити Запис..."
    EditorContextActionOpenMoveEntryDialog -> "Перемістити Запис до..."
    EditorContextActionCopyEntryName -> "Копіювати Назву Запису в Буфер Обміну"
    EditorContextActionFilterByEntryName -> "Фільтрувати за Назвою Запису"
    EditorContextActionCopySampleName -> "Копіювати Назву Зразка в Буфер Обміну"
    EditorContextActionFilterBySampleName -> "Фільтрувати за Назвою Зразка"
    EditorContextActionFilterByTag -> "Фільтрувати за Тегом"
    EditorContextActionFilterStarred -> "Фільтрувати Позначені Зірочкою Записи"
    EditorContextActionFilterUnstarred -> "Фільтрувати Не Позначені Зірочкою Записи"
    EditorContextActionFilterDone -> "Фільтрувати Виконані Записи"
    EditorContextActionFilterUndone -> "Фільтрувати Невиконані Записи"
}
