package testutil

import java.io.File

/**
 * Access to the fixture files under `src/jvmTest/resources/fixtures`.
 *
 * A fixture folder contains the text files (label files, configs) of a sample project. Since wav files are not
 * committed, they are generated by [TestWav] when the fixture is deployed to a working directory via [deploy].
 */
object TestFixtures {

    // resolved via a marker file because a directory lookup could be shadowed by a package with the same name
    private val root: File
        get() = File(requireNotNull(TestFixtures::class.java.getResource("/fixtures/root.marker")).toURI()).parentFile

    fun getDir(name: String): File = root.resolve(name).also {
        require(it.isDirectory) { "Fixture directory not found: ${it.absolutePath}" }
    }

    /**
     * Copies the fixture folder [name] into [target] and generates the wav files given as [wavFiles] (paths relative
     * to the fixture root, e.g. `C4/_a_ka.wav`).
     *
     * @return [target] for chaining.
     */
    fun deploy(
        name: String,
        target: File,
        wavFiles: List<String> = emptyList(),
        wavDurationMs: Int = 1000,
    ): File {
        getDir(name).copyRecursively(target, overwrite = true)
        wavFiles.forEach { TestWav.write(target.resolve(it), durationMs = wavDurationMs) }
        return target
    }
}
