import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the docs folder structure.
// Use `sidebar_position` in the front matter and `_category_.json` files to control ordering.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
